### ISSUE TITLE
ca-cert option in flux-instance

### ISSUE THREAD

**Issue by krishau99** [controlplaneio-fluxcd/flux-operator#112]
Hi!

I have custom signed certificates and will need to add a custom ca to reach my git instance at `spec.distribution.registry`. 

With `flux bootstrap` there is an option to provide a `--ca-file`. I could not find this option implemented in the `flux-instance`. Am I missing something, or do you have any tips on how to provide this in the `flux-instance` manifest? If its not implemented, is this a planned feature for the near future?

**Comment by stefanprodan** [comment]
The `spec.distribution.registry` points to the container registry where the Flux images are. Are you maybe referring to the `spec.sync` section, that’s the one holding the Git configuration?

**Comment by krishau99** [comment]
Yes, that is correct. It would be the `spec.sync` section. So that would mean an option to add the `--ca-file` option in the flux-instance under that section.

**Comment by stefanprodan** [comment]
You would just add the CA to the Git auth secret, there is no need to configure anything in the sync besides setting pullSecret. See https://fluxcd.io/flux/components/source/gitrepositories/#https-certificate-authority

**Comment by stefanprodan** [comment]
There is a dedicated command that you can use to generate the secret `flux create secret git flux-system -u -p --ca-crt-file`
