### ISSUE TITLE
Create a PodMonitor CR for a FluxInstance

### ISSUE THREAD

**Issue by jfroy** [controlplaneio-fluxcd/flux-operator#115]
The operator currently adds Prometheus scrape annotations, but not all clusters enable annotation pod discovery, and some alternative stacks like VictoriaMetrics require additional configuration. It would be nice if the operator could also, optionally, emit a `PodMonitor` CR for a `FluxInstance`.

**Comment by stefanprodan** [comment]
This would create a chicken and egg problem, Flux should be deploying the Prom Operator CRDs, so you can't include any CRs in the Flux Instance as they will fail. The right approach is after the FluxInstance gets created on an empty cluster, for Flux to deploy the monitoring stack and the PodMonitor from your own repo. Here is an example:  https://github.com/fluxcd/flux2-monitoring-example

**Comment by jfroy** [comment]
Ah yes that does make sense. To some extent the operator could watch for the presence of the Prometheus CRDs and then create the CR, but that's probably not worth it complexity.
