### ISSUE TITLE
Allow a shorter reconciliation interval for the artifact

### ISSUE THREAD

**Issue by matheuscscp** [controlplaneio-fluxcd/flux-operator#121]
Today we have the annotation `fluxcd.controlplane.io/reconcileEvery` for configuring the interval with which flux-operator will reconcile a `FluxInstance`, which defaults to `1h`. The server-side apply dry-run can be resource intensive, so this interval should indeed be kept around this amount of time.

However, for pulling the OCI artifact containing the latest images (i.e. with the latest CVE patches), users may want a shorter interval, e.g. `2m`.

# Proposal

Create a new reconciler that runs on a separate interval controlled by the annotation `fluxcd.controlplane.io/reconcileArtifactEvery` defaulting to `10m`. This reconciler will compare the digest of the artifact with the one stored in the `FluxInstance` status and annotate the object to request a reconciliation in case of mismatch.

**Comment by stefanprodan** [comment]
A first step towards this, would be to introduce a new optional field in status called `lastArtifactRevision` with the values set from: https://github.com/controlplaneio-fluxcd/flux-operator/blob/3d483b72342f0d7d667e87608fe15160864dcd75/internal/controller/fluxinstance_controller.go#L234

This status fields should only be set if `.spec.distribution.artifact` exists, when the spec changes, and the artifact field is removed, so should the status field. This status field will act as a enabler of the artifact reconciler, if status does not contain `lastArtifactRevision`, then the reconciler should exit early.
