### ISSUE TITLE
`networkPolicy` is documented as true/enabled by default, but isn't

### ISSUE THREAD

**Issue by kingdonb** [controlplaneio-fluxcd/flux-operator#51]
I'm testing flux-operator 0.6 and I've noticed that setting:

```
cluster:
  networkPolicy: true
```

induces the operator to install `NetworkPolicy` resources, the expected default

but the CRD default:

```yaml
cluster: ~
```

does not set `NetworkPolicy` to true, so the resources aren't included. This is unexpected!

**Comment by stefanprodan** [comment]
Thanks @kingdonb for the bug report, this will be fixed in the next release. Until then, you have to explicitly set the cluster field.
