### ISSUE TITLE
How to make operator watch all namespaces

### ISSUE THREAD

**Issue by kvaps** [controlplaneio-fluxcd/flux-operator#55]
We want to deploy separate flux instance for every tenant, but it seems fluxcd-operator does not see any instances created outside of it's `WATCH_NAMESPACE`. How to make operator watch and handle FluxcdInstances from all namespaces?

**Comment by stefanprodan** [comment]
Flux is not made to be deployed per namespace. You would set cluster.multitenant true. See here how multi-tenancy works https://fluxcd.io/flux/installation/configuration/multitenancy/

**Comment by kvaps** [comment]
Got it. Can I target fluxcd to multiple namespaces?

Eg. one flux serves everything in `cozy-*`
Second for `tenant-user1` and `tenant-user1-extra`

**Comment by kvaps** [comment]
There is probably an option to use label selectors, eg. `--watch-label-selector` for the controllers.

https://fluxcd.io/flux/installation/configuration/sharding/

So we need to write webhook which would automatically append the needed labels

**Comment by stefanprodan** [comment]
Why do you need sharding? Are you deploying 10K apps? Isn’t vertical scaling working for you? 

For tentat isolation, you would only need to provision SA/RBAC in each namespace.

**Comment by kvaps** [comment]
Not yet. We just want to enhance parallel resources processing and minimize the failure domain to specific tenants.
